/*
===========================================================================
    Copyright (C) 2018-2022 Adriano Di Dio.
    
    MOHLevelViewer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MOHLevelViewer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with MOHLevelViewer.  If not, see <http://www.gnu.org/licenses/>.
===========================================================================
*/ 

#ifndef __CONFIG_H_
#define __CONFIG_H_

#define CONFIG_FILE_HEADER  "This File is automatically generated by MOHLevelViewer."
typedef struct Config_s {
    char *Name;
    char *Value;
    char *Description;
    struct Config_s *Next;
} Config_t;

extern Config_t *ConfigList;

void ConfigInit();
int ConfigSet(char *Name,char *Value);
int ConfigRegister(char *Name,char *Value,char *Description);
void ConfigSaveSettings();
void ConfigFree();
#endif//__CONFIG_H_
