/*
===========================================================================
    Copyright (C) 2018-2023 Adriano Di Dio.
    
    Medal-Of-Honor-PSX-File-Viewer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Medal-Of-Honor-PSX-File-Viewer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Medal-Of-Honor-PSX-File-Viewer.  If not, see <http://www.gnu.org/licenses/>.
===========================================================================
*/ 

#ifndef __CONFIG_H_
#define __CONFIG_H_

#define CONFIG_FILE_HEADER  "This file is automatically generated."
typedef struct Config_s {
    char *Name;
    char *Value;
    int   IValue;
    float FValue;
    char *Description;
    struct Config_s *Next;
} Config_t;

extern Config_t *ConfigList;

void        ConfigInit();
int         ConfigSet(const char *Name,const char *Value);
int         ConfigSetNumber(const char *Name,float Value);
Config_t    *ConfigGet(const char *Name);
int         ConfigRegister(const char *Name,const char *Value,const char *Description);
void        ConfigSaveSettings();
void        ConfigFree();
#endif//__CONFIG_H_
